yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='groups'
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
# Create your views here.
from .models import Post, Group


def index(request):
    text = 'Последние обновления на сайте'
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию
    # (от больших значений к меньшим)
    posts = Post.objects.order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'title': text,
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)
    text = f'Записи сообщества {group}'

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'title': text,
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html> 
{% load static %}
<html lang="ru">          
  <head> 
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <h1> {{ text }}</h1>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
  <div class="footer-copyright text-center py-3">© 2020 Copyright 
    <p><span style="color:red">Ya</span>tube</p> 
  </div>    
</footer>

yatube/templates/includes/header.html
 <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      {% load static %}
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>
      <title>
        {% block title %}
        {{ title }}
        {% endblock %}
      </title>

yatube/templates/posts/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
{% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <p>
          {{ group }}
        </p>
        <article>
          <p>
            {% for post in posts %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <p>{{ post.text }}</p>    
          </p>
        </article>
        <hr>
        {% endfor %} 
        <!-- под последним постом нет линии -->
      </div>
    {% endblock %}

yatube/templates/posts/index.html
<!-- templates/posts/index.html -->
<!DOCTYPE html> 
{% extends 'base.html' %}
{% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5"> 
        <article>
          {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
  {% if post.group %}   
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %} 
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
        </article>
        <!-- под последним постом нет линии -->
      </div>  
{% endblock %}